# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    name: Test
    strategy:
    # Keeps running to check if other tests pass/fail
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 wheel
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --show-source --statistics
    - name: Build package
      run: |
        python setup.py sdist bdist_wheel


  # https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
#   publish-pypi:
#     name: Pypi
#     if: startsWith(github.ref, 'refs/tags')
#     needs:
#       # Only publish if other jobs passed
#       - test
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-python@v2
#       - name: Build package
#         run: |
#           python -mpip install wheel
#           python setup.py sdist bdist_wheel
#       - name: Publish to PyPI
#         uses: pypa/gh-action-pypi-publish@v1.3.0
#         with:
#           password: ${{ secrets.PYPI_PASSWORD }}
